Model: resnet18
Dataset: cifar100
Regularizer:
  name: SO
  fc: false
  onlyconv: true
  milestone:
    lr_MS: [60, 110, 150, 180]
    lr: [1e-1, 2e-2, 4e-3, 2e-4]
    reg_MS: [20, 50, 70, 120]
    rr: [1e-1, 1e-3, 1e-4, 1e-6, 0]
    wr: [1e-8, 5e-4, 5e-4, 5e-4, 5e-4]
Train:
  rtn: 1e-1
  theta: 1.5708
  epochs: 200
  batchsize: 128
  warmup: 1
