Model: resnet34
Dataset: cifar100
Regularizer:
  name: base
  optimizer: sgd
  log: './log/performance2/'
  seed: 1000
  fc: false
  kern: false
  conv: true
  milestone:
    lr_MS: [60, 110, 150, 180]
    lr: [1e-1, 2e-2, 4e-3, 8e-4, 2e-4] # learning ratio
    reg_MS: []
    rr: [] # regularization ratio to be multiplied by lr
    wr: [5e-4] # weight decay
Train:
  rtn: 1e-1 # thetaloss (over normloss, only for ADK, AKC) ratio to be multiplied by lr and rr
  double: false
  theta: 1.5708
  epochs: 200
  batchsize: 256