Model: wideResnet
Dataset: cifar10
Regularizer:
  name: OCNN
  optimizer: sgd
  log: './log/performance2/'
  seed: 1000
  fc: false
  kern: false
  conv: true
  milestone:
    lr_MS: [60, 120, 160]
    lr: [1e-1, 2e-2, 4e-3, 8e-4] # learning ratio
    reg_MS: [20, 50, 70, 120]
    rr: [1e-2, 2e-3, 4e-4, 8e-5, 0] # regularization ratio to be multiplied by lr
    wr: [1e-8, 5e-4, 5e-4, 5e-4, 5e-4] # weight decay
Train:
  rtn: 1e-1 # thetaloss (over normloss) ratio to be multiplied by lr and rr
  double: false
  theta: 1.5708
  epochs: 200
  batchsize: 128